<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Entity\Review;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository
{
}
