<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
}
