services:
  app:
    image: demo/frankenphp:dev
    build:
      target: dev
    environment:
      CADDY_GLOBAL_OPTIONS: debug
    volumes:
      - ./etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - php_vendor:/app/vendor
      - ./src:/app
volumes:
  php_vendor:
