services:
  app:
    image: demo/frankenphp:dev
    build:
      target: dev
      cache_from:
        - type=gha,scope=frankenphp
      cache_to:
        - type=gha,scope=frankenphp,mode=max
    environment:
      CADDY_GLOBAL_OPTIONS: debug
    volumes:
      - ./etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./src:/app
