services:
  web:
    volumes:
      - php_var:/var/www/html/var
      - php_vendor:/var/www/html/vendor
      - ./src:/var/www/html
  app:
    build:
      target: dev
    volumes:
      - php_var:/var/www/html/var
      - php_vendor:/var/www/html/vendor
      - ./src:/var/www/html
volumes:
  php_var:
  php_vendor:
