services:
  web:
    volumes:
      - ./src:/var/www/html
      # - php_var:/var/www/html/var
      # - php_vendor:/var/www/html/vendor
  app:
    build:
      target: dev
    volumes:
      - ./src:/var/www/html
      # - php_var:/var/www/html/var
      # - php_vendor:/var/www/html/vendor
      # volumes: 
      #   php_var:
      #   php_vendor:
