services:
  web:
    volumes:
      - php_src:/var/www/html
  app:
    build:
      target: prod
    image: registry.$DOMAIN_NAME/php-doctrine-prod
    volumes:
      - php_src:/var/www/html
volumes:
  php_src:
