services:
  app:
    build:
      target: dev
      args:
        APP_ENV: dev
      cache_from:
        - type=gha,scope=compil
      cache_to:
        - type=gha,scope=compil,mode=max
    volumes:
      - ./src:/var/www/html
