services:
  web:
    depends_on:
      - app
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        NGINX_IMAGE:
    image: $WEB_IMAGE
    ports:
      - 80:80
    volumes:
      - php_run:/var/run/php
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://localhost' ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
  app:
    build:
      context: .
      dockerfile: $DOCKERFILE
      args:
        OS_IMAGE:
        PHP_VERSION_NUMBER:
        PHP_DIRECTORY:
    image: $APP_IMAGE
    volumes:
      - php_run:/var/run/php
    healthcheck:
      test: [ 'CMD', 'pidof', 'php-fpm' ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
volumes:
  php_run:
