ARG OS_IMAGE=centos:centos8

FROM $OS_IMAGE AS base

RUN yum update -y -q\
  && yum install -y libxml2-devel sqlite-devel libzip-devel\
  && yum clean all

FROM base AS build

ARG PHP_VERSION_NUMBER
ARG PHP_DIRECTORY
ARG APP_ENV

RUN yum update -y -q\
  && yum groupinstall -y 'Development tools'\
  && yum --enablerepo=PowerTools install -y re2c\
  && yum install -y git\
  && yum clean all

WORKDIR /usr/local/src/php

COPY sh/php_install.sh ..
RUN sh ../php_install.sh

COPY ./etc/php-fpm.conf /usr/local/php/etc/php-fpm.d/www.conf

FROM base AS dev

ARG PHP_DIRECTORY

COPY --from=build ${PHP_DIRECTORY} ${PHP_DIRECTORY}

RUN ln -s ${PHP_DIRECTORY}/bin/php /usr/local/bin\
  && ln -s ${PHP_DIRECTORY}/sbin/php-fpm /usr/local/bin

COPY sh/wrapper_script.sh /usr/local/bin/wrapper_script.sh
RUN chmod +x /usr/local/bin/wrapper_script.sh

CMD [ "sh", "/usr/local/bin/wrapper_script.sh" ]

FROM dev AS prod

COPY ./src /var/www/html
