ARG OS_IMAGE=debian:bookworm-slim

FROM $OS_IMAGE AS base

ARG PHP_DIR

RUN apt-get update -qq\
  && apt-get install -y --no-install-recommends libxml2 libsqlite3-0 libzip4\
  && rm -rf /var/lib/apt/lists/*

RUN ln -s ${PHP_DIR}/bin/php /usr/local/bin\
  && ln -s ${PHP_DIR}/sbin/php-fpm /usr/local/bin

COPY sh/wrapper_script.sh /usr/local/bin/wrapper_script.sh
RUN chmod +x /usr/local/bin/wrapper_script.sh

WORKDIR $PHP_DIR

CMD [ "sh", "/usr/local/bin/wrapper_script.sh" ]

FROM base AS base-builder

ARG PHP_SRC_DIR
ARG PHP_VERSION_NUMBER
ARG PHP_DIR
ARG PHP_INI_DIR

WORKDIR $PHP_SRC_DIR

COPY sh/php_install.sh ..

RUN apt-get update -qq\
  && apt-get install -y --no-install-recommends\
    autoconf build-essential bison re2c pkg-config git\
    libxml2-dev libsqlite3-dev libzip-dev\
  && sh ../php_install.sh\
  && apt-get purge -y\
    autoconf build-essential bison re2c pkg-config git\
    libxml2-dev libsqlite3-dev libzip-dev\
  && rm -rf /var/lib/apt/lists/*

RUN cp ${PHP_DIR}/etc/php-fpm.conf.default ${PHP_DIR}/etc/php-fpm.conf
COPY ./etc/php-fpm.conf $PHP_INI_DIR-fpm.d/www.conf

FROM base AS dev

ARG PHP_DIR
ARG PHP_SRC_DIR
ARG PHP_INI_DIR

COPY --from=base-builder ${PHP_DIR} ${PHP_DIR}
COPY --from=base-builder ${PHP_SRC_DIR}/php.ini-development ${PHP_INI_DIR}/php.ini

COPY ./src /var/www/html

FROM base AS prod

ARG PHP_DIR
ARG PHP_SRC_DIR
ARG PHP_INI_DIR

COPY --from=base-builder ${PHP_DIR} ${PHP_DIR}
COPY --from=base-builder ${PHP_SRC_DIR}/php.ini-production ${PHP_INI_DIR}/php.ini

COPY ./src /var/www/html
