ARG OS_IMAGE=alpine:3.23.4

FROM $OS_IMAGE AS base

ARG PHP_DIR

RUN apk add --no-cache\
  libgcc libxml2 sqlite-libs libzip

RUN ln -s ${PHP_DIR}/bin/php /usr/local/bin\
  && ln -s ${PHP_DIR}/sbin/php-fpm /usr/local/bin

COPY sh/wrapper_script.sh /usr/local/bin/wrapper_script.sh
RUN chmod +x /usr/local/bin/wrapper_script.sh

WORKDIR $PHP_DIR

CMD [ "sh", "/usr/local/bin/wrapper_script.sh" ]

FROM base AS base-builder

ARG PHP_SRC_DIR
ARG PHP_VERSION_NUMBER
ARG PHP_DIR
ARG PHP_INI_DIR

WORKDIR $PHP_SRC_DIR

COPY sh/php_install.sh ..

RUN apk add --no-cache --virtual .build-deps\
  autoconf build-base bison re2c linux-headers git\
  libxml2-dev sqlite-dev libzip-dev\
  && sh ../php_install.sh\
  && apk del .build-deps

RUN cp ${PHP_DIR}/etc/php-fpm.conf.default ${PHP_DIR}/etc/php-fpm.conf
COPY ./etc/php-fpm.conf $PHP_INI_DIR-fpm.d/www.conf

FROM base AS dev

ARG PHP_DIR
ARG PHP_SRC_DIR
ARG PHP_INI_DIR

COPY --from=base-builder ${PHP_DIR} ${PHP_DIR}
COPY --from=base-builder ${PHP_SRC_DIR}/php.ini-development ${PHP_INI_DIR}/php.ini

COPY ./src /var/www/html

FROM base AS prod

ARG PHP_DIR
ARG PHP_SRC_DIR
ARG PHP_INI_DIR

COPY --from=base-builder ${PHP_DIR} ${PHP_DIR}
COPY --from=base-builder ${PHP_SRC_DIR}/php.ini-production ${PHP_INI_DIR}/php.ini

COPY ./src /var/www/html
