ARG PHP_IMAGE=php:8.5.10-fpm-alpine

FROM $PHP_IMAGE AS base

ARG PHP_REDIS_VERSION=6.3.0

#redis
RUN apk add --no-cache --virtual .build-deps autoconf build-base\
  && pecl install redis-$PHP_REDIS_VERSION\
  && docker-php-ext-enable redis\
  && apk del .build-deps

COPY ./etc/php-fpm/www.conf $PHP_INI_DIR-fpm.d/zz-docker.conf

WORKDIR /var/www/html

FROM base AS base-builder

#xdebug
WORKDIR /tmp/xdebug
RUN apk add --no-cache --virtual .build-deps autoconf build-base linux-headers\
  && wget -q https://xdebug.org/files/xdebug-3.5.3.tgz\
  && tar --strip-components=1 -xzf xdebug-3.5.3.tgz\
  && phpize\
  && ./configure --enable-xdebug\
  && make\
  && make install\
  && docker-php-ext-enable xdebug\
  && apk del .build-deps\
  && rm -rf /tmp/xdebug

FROM base-builder AS dev

COPY ./src /var/www/html

RUN cp "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

FROM base AS prod

COPY ./src /var/www/html

RUN cp "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
