services:
  app:
    build:
      context: .
      dockerfile: dockerfile/php.Dockerfile
      args:
        PHP_IMAGE:
        GITHUB_TOKEN:
    image: $APP_IMAGE
  web:
    depends_on:
      - app
    build:
      context: .
      dockerfile: dockerfile/nginx.Dockerfile
      args:
        NGINX_IMAGE:
    image: $WEB_IMAGE
    ports:
      - 80:80
