services:
  php:
    build:
      target: dev
    volumes:
      - ./src:/usr/share/nginx/html
  nginx:
    build:
      target: dev
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
