services:
  php:
    build:
      context: .
      dockerfile: dockerfile/php.Dockerfile
      args:
        PHP_IMAGE:
        GITHUB_TOKEN:
  nginx:
    depends_on:
      - php
    build:
      context: .
      dockerfile: dockerfile/nginx.Dockerfile
      args:
        NGINX_IMAGE:
    ports:
      - 80:80
